### ISSUE TITLE
ngqgis dumps core on load

### ISSUE THREAD

**Issue by Komzpa** [nextgis/nextgisqgis#51]
logbt output:
```
kom@junocat ~ % logbt -- ngqgis
[logbt] using corefile location: /tmp/logbt-coredumps
[logbt] using core_pattern: core.%p.%E
Plugin path: /usr/lib/x86_64-linux-gnu/qt4/plugins
Prefix: /usr
Warning: loading of qgis translation failed [/usr/share/ngqgis/i18n//qgis_be_BY]
Warning: loading of qt translation failed [/usr/share/qt4/translations/qt_be_BY]
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
Warning: Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
Warning: Object::connect: No such signal QgsMergedBookmarksTableModel::&QgsMergedBookmarksTableModel::selectItem( const QModelIndex &index )
Warning: Object::connect:  (receiver name: 'QgsBookmarksBase')
Warning: QCss::Parser - Failed to load file  "/style.qss" 
Warning: QLayout: Attempting to add QLayout "" to QgsPanelWidgetStack "mWidgetStack", which already has a layout
/usr/local/bin/logbt: line 270: 21643 Збой сэгмэнтацыі       (core dumped) LOGBT_PID=$$ $*
[logbt] saw 'ngqgis' exit with code:139 (SEGV)
[logbt] Found corefile at /tmp/logbt-coredumps/core.21643.!usr!bin!ngqgis
[New LWP 21643]
[New LWP 21644]
[New LWP 21645]
[New LWP 21646]
[New LWP 21648]
[New LWP 21649]
[New LWP 21650]
[New LWP 21651]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `ngqgis'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62      ../sysdeps/x86_64/multiarch/strlen-avx2.S: файл ці тэчка ня йснуе.
[Current thread is 1 (Thread 0x7f149d5d1200 (LWP 21643))]

Thread 8 (Thread 0x7f14663b3700 (LWP 21651)):
#0  0x00007f1499ae3bf9 in __GI___poll (fds=0x7f1410004e20, nfds=1, timeout=9999) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f14990c5439 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f14990c554c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f149d0e320e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007f149d0b112f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007f149d0b1495 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007f149cfa0549 in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007f149cfa2e3c in  () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007f14997b76db in start_thread (arg=0x7f14663b3700) at pthread_create.c:463
#9  0x00007f1499af088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7f1466ffd700 (LWP 21650)):
#0  0x00007f14997bdf85 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f1466ffc390, expected=0, futex_word=0x7f14741034cc) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x00007f14997bdf85 in __pthread_cond_wait_common (abstime=0x7f1466ffc390, mutex=0x7f1474103478, cond=0x7f14741034a0) at pthread_cond_wait.c:539
#2  0x00007f14997bdf85 in __pthread_cond_timedwait (cond=0x7f14741034a0, mutex=0x7f1474103478, abstime=0x7f1466ffc390) at pthread_cond_wait.c:667
#3  0x00007f1495d0932a in WTF::ThreadCondition::timedWait(WTF::Mutex&, double) () at /usr/lib/x86_64-linux-gnu/libQtWebKit.so.4
#4  0x00007f14959f9285 in  () at /usr/lib/x86_64-linux-gnu/libQtWebKit.so.4
#5  0x00007f1495d08cc6 in  () at /usr/lib/x86_64-linux-gnu/libQtWebKit.so.4
#6  0x00007f14997b76db in start_thread (arg=0x7f1466ffd700) at pthread_create.c:463
#7  0x00007f1499af088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f14677fe700 (LWP 21649)):
#0  0x00007f14997bd9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f1496768698) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007f14997bd9f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x7f1496768648, cond=0x7f1496768670) at pthread_cond_wait.c:502
#2  0x00007f14997bd9f3 in __pthread_cond_wait (cond=0x7f1496768670, mutex=0x7f1496768648) at pthread_cond_wait.c:655
#3  0x00007f1495cd66fd in  () at /usr/lib/x86_64-linux-gnu/libQtWebKit.so.4
#4  0x00007f1495cd6759 in  () at /usr/lib/x86_64-linux-gnu/libQtWebKit.so.4
#5  0x00007f14997b76db in start_thread (arg=0x7f14677fe700) at pthread_create.c:463
#6  0x00007f1499af088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f1467fff700 (LWP 21648)):
#0  0x00007f1499ae3bf9 in __GI___poll (fds=0x7f1460004f20, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f14990c5439 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f14990c554c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f149d0e320e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007f149d0b112f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007f149d0b1495 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007f149cfa0549 in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007f149d0911c3 in  () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007f149cfa2e3c in  () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007f14997b76db in start_thread (arg=0x7f1467fff700) at pthread_create.c:463
#10 0x00007f1499af088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f147499d700 (LWP 21646)):
#0  0x00007f1499ae603f in __GI___select (nfds=5, readfds=0x7f147499c340, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00007f149d08d5cf in  () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007f149cfa2e3c in  () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00007f14997b76db in start_thread (arg=0x7f147499d700) at pthread_create.c:463
#4  0x00007f1499af088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f14752c7700 (LWP 21645)):
#0  0x00007f1499ae3bf9 in __GI___poll (fds=0x7f1468004f20, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f14990c5439 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f14990c554c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f149d0e320e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007f149d0b112f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007f149d0b1495 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007f149cfa0549 in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007f149d0911c3 in  () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007f149cfa2e3c in  () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007f14997b76db in start_thread (arg=0x7f14752c7700) at pthread_create.c:463
#10 0x00007f1499af088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f147697a700 (LWP 21644)):
#0  0x00007f1499ae3bf9 in __GI___poll (fds=0x7f1470005440, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f14990c5439 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f14990c554c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f149d0e320e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007f149d0b112f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007f149d0b1495 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007f1492d2ac5f in QCA::SyncThread::run() () at /usr/lib/x86_64-linux-gnu/libqca.so.2
#7  0x00007f149cfa2e3c in  () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007f14997b76db in start_thread (arg=0x7f147697a700) at pthread_create.c:463
#9  0x00007f1499af088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f149d5d1200 (LWP 21643)):
#0  0x00007f1499b5d5a1 in __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007f141d7ade11 in PyString_FromFormatV () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#2  0x00007f141d8480ec in PyErr_Format () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#3  0x00007f141d19c692 in  () at /usr/lib/python2.7/dist-packages/sip.x86_64-linux-gnu.so
#4  0x00007f1417509776 in init_core () at /usr/lib/python2.7/dist-packages/qgis/_core.so
#5  0x00007f141d7c9cab in _PyImport_LoadDynamicModule () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#6  0x00007f141d84dafe in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#7  0x00007f141d7cae91 in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#8  0x00007f141d7cb45c in PyImport_ImportModuleLevel () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#9  0x00007f141d72dde4 in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#10 0x00007f141d6cd333 in PyObject_Call () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#11 0x00007f141d8577a7 in PyEval_CallObjectWithKeywords () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#12 0x00007f141d723ac9 in PyEval_EvalFrameEx () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#13 0x00007f141d858278 in PyEval_EvalCodeEx () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#14 0x00007f141d720029 in PyEval_EvalCode () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#15 0x00007f141d8481cc in PyImport_ExecCodeModuleEx () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#16 0x00007f141d84d462 in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#17 0x00007f141d84da3e in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#18 0x00007f141d84dd4a in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#19 0x00007f141d7cae91 in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#20 0x00007f141d7cb45c in PyImport_ImportModuleLevel () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#21 0x00007f141d72dde4 in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#22 0x00007f141d6cd333 in PyObject_Call () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#23 0x00007f141d8577a7 in PyEval_CallObjectWithKeywords () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#24 0x00007f141d723ac9 in PyEval_EvalFrameEx () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#25 0x00007f141d858278 in PyEval_EvalCodeEx () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#26 0x00007f141d720029 in PyEval_EvalCode () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#27 0x00007f141d8481cc in PyImport_ExecCodeModuleEx () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#28 0x00007f141d84d462 in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#29 0x00007f141d84da3e in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#30 0x00007f141d84dd4a in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#31 0x00007f141d7cae91 in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#32 0x00007f141d7cb392 in PyImport_ImportModuleLevel () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#33 0x00007f141d72dde4 in  () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#34 0x00007f141d6cd333 in PyObject_Call () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#35 0x00007f141d8577a7 in PyEval_CallObjectWithKeywords () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#36 0x00007f141d723ac9 in PyEval_EvalFrameEx () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#37 0x00007f141d858278 in PyEval_EvalCodeEx () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#38 0x00007f141d720029 in PyEval_EvalCode () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#39 0x00007f141d7c3546 in PyRun_StringFlags () at /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#40 0x00007f141dbf9ac4 in QgsPythonUtilsImpl::runStringUnsafe(QString const&, bool) () at /usr/lib/x86_64-linux-gnu/libngqgis_python.so.2.18.19
#41 0x00007f141dbffa76 in QgsPythonUtilsImpl::runString(QString const&, QString, bool) () at /usr/lib/x86_64-linux-gnu/libngqgis_python.so.2.18.19
#42 0x00007f141dbfe135 in QgsPythonUtilsImpl::checkSystemImports() () at /usr/lib/x86_64-linux-gnu/libngqgis_python.so.2.18.19
#43 0x00007f141dbff7dd in QgsPythonUtilsImpl::initPython(QgisInterface*) () at /usr/lib/x86_64-linux-gnu/libngqgis_python.so.2.18.19
#44 0x00007f149a8c6417 in NGQgisApp::loadPythonSupport() () at /usr/lib/x86_64-linux-gnu/libngqgis_app.so.2
#45 0x00007f149a8c7df5 in NGQgisApp::NGQgisApp(QSplashScreen*, bool, bool, QWidget*, QFlags<Qt::WindowType>) () at /usr/lib/x86_64-linux-gnu/libngqgis_app.so.2
#46 0x000055f45f314bb7 in main ()
```

**Comment by Komzpa** [comment]
resolved by hand upgrading packages from artful-on-bionic to bionic-on-bionic.

**Comment by BishopGIS** [comment]
Reproduced on same situation - upgrade from Artful to Bionic. Upgrade to bionic ngqgis helps.
